version: "3"

services:
  openfisca:
    build:
      context: .
    restart: always
    labels: 
      - traefik.http.routers.openfisca.rule=Host(`rac.g0v.nz`)
      - traefik.http.routers.openfisca.tls=true
      - traefik.http.routers.openfisca.tls.certresolver=lets-encrypt
      - traefik.port=5000
    networks:
      - web
    volumes:
      - .:/openfisca

networks:
  web:
    external: true
